output "deployment_mode" {
  description = "Whether the stack is running in single-account reviewer mode or distinct multi-account mode."
  value       = local.single_account_mode ? "single-account-reviewer" : "multi-account"
}

output "name_prefix" {
  description = "Effective name prefix used for sandbox isolation (empty for exact assignment names)."
  value       = local.name_prefix
}

output "resolved_account_ids" {
  description = "Effective Account A / Account B IDs after reviewer defaults."
  value = {
    account_a = local.account_a_id
    account_b = local.account_b_id
  }
}

output "instance_ids_by_name" {
  description = "Task 1 output: instance name to EC2 instance ID."
  value       = var.enable_ec2 ? module.ec2_fleet[0].instance_ids_by_name : {}
}

output "private_ips_by_name" {
  description = "Task 1 output: instance name to private IP."
  value       = var.enable_ec2 ? module.ec2_fleet[0].private_ips_by_name : {}
}

output "protected_instance_names" {
  description = "Instances protected by lifecycle.prevent_destroy."
  value       = var.enable_ec2 ? module.ec2_fleet[0].protected_instance_names : []
}

output "account_a_role_a_arn" {
  description = "Account A roleA ARN."
  value       = var.enable_iam ? module.account_a_iam[0].role_a_arn : null
}

output "account_a_role_b_arn" {
  description = "Account A roleB ARN trusted by Account B roleC."
  value       = var.enable_iam ? module.account_a_iam[0].role_b_arn : null
}

output "account_b_role_c_arn" {
  description = "Account B roleC ARN."
  value       = var.enable_iam ? module.account_b_iam[0].role_c_arn : null
}

output "role_c_bucket_name" {
  description = "S3 bucket fully accessible by roleC."
  value       = var.enable_iam ? module.account_b_iam[0].bucket_name : null
}

output "ci_policy_json" {
  description = "Task 4 least-privilege CI policy JSON generated by Terraform."
  value       = var.enable_iam ? module.account_a_iam[0].ci_policy_json : null
}

output "generated_ssh_private_key_pem" {
  description = "Ephemeral SSH private key when generate_ssh_key=true. Sandbox only."
  value       = try(tls_private_key.fleet[0].private_key_openssh, null)
  sensitive   = true
}

output "sandbox_smoke_commands" {
  description = "Copy-paste checks after a sandbox apply."
  value = var.enable_iam ? {
    whoami                 = "aws sts get-caller-identity"
    assume_role_b          = "aws sts assume-role --role-arn $(terraform output -raw account_a_role_b_arn) --role-session-name sandbox-roleb"
    describe_role_c_bucket = "aws s3api head-bucket --bucket $(terraform output -raw role_c_bucket_name)"
  } : {}
}

output "reviewer_next_steps" {
  description = "Operational hints after apply."
  value = {
    offline_validate = "make reviewer-validate"
    sandbox_up       = "make sandbox-up"
    sandbox_down     = "make sandbox-down"
    destroy_hint     = "For protected EC2 (ledger-a), clear protected/termination protection before destroy"
  }
}
