#!/usr/bin/env bash
# One-command sandbox apply in the reviewer's AWS account (or shared sandbox).
# Default: IAM + roleC bucket only (Tasks 2 concepts via local state, Tasks 3–4 live).
# Optional EC2: SANDBOX_WITH_EC2=1 ./scripts/sandbox-up.sh
set -euo pipefail

# shellcheck source=lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
cd "${ROOT}"

WITH_EC2="${SANDBOX_WITH_EC2:-0}"
AUTO_APPROVE="${SANDBOX_AUTO_APPROVE:-0}"
AWS_REGION_VALUE="${AWS_REGION:-${AWS_DEFAULT_REGION:-ap-south-1}}"

./scripts/preflight.sh sandbox

ensure_sandbox_dir

if [[ -f "${SANDBOX_META}" ]]; then
  # shellcheck disable=SC1090
  source "${SANDBOX_META}"
  log "Reusing existing sandbox prefix: ${NAME_PREFIX}"
else
  SUFFIX="$(python3 - <<'PY'
import secrets, string
alphabet = string.ascii_lowercase + string.digits
print("".join(secrets.choice(alphabet) for _ in range(6)))
PY
)"
  NAME_PREFIX="arrise-sbx-${SUFFIX}"
  cat > "${SANDBOX_META}" <<EOF
NAME_PREFIX=${NAME_PREFIX}
AWS_REGION_VALUE=${AWS_REGION_VALUE}
CREATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
  log "Created sandbox prefix: ${NAME_PREFIX}"
fi

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"

{
  cat "${ROOT}/config/sandbox.tfvars"
  cat <<EOF

# --- generated by scripts/sandbox-up.sh (do not edit by hand) ---
aws_region   = "${AWS_REGION_VALUE}"
name_prefix  = "${NAME_PREFIX}"
owner        = "reviewer-${ACCOUNT_ID}"
enable_ec2   = ${WITH_EC2}
enable_iam   = true
EOF
} > "${SANDBOX_TFVARS}"

log "Sandbox tfvars written to .sandbox/terraform.tfvars"
log "Mode: $([[ "${WITH_EC2}" == "1" ]] && echo 'IAM + cheap EC2' || echo 'IAM-only (recommended)')"

log "terraform init -backend=false (local state — ideal for sandbox)"
terraform init -backend=false -input=false -upgrade >/dev/null

PLAN_FILE="${SANDBOX_DIR}/sandbox.tfplan"
log "terraform plan"
terraform plan \
  -var-file="${SANDBOX_TFVARS}" \
  -out="${PLAN_FILE}" \
  -input=false

if [[ "${AUTO_APPROVE}" != "1" ]]; then
  printf '\nApply this sandbox plan? [y/N] '
  read -r answer
  [[ "${answer}" == "y" || "${answer}" == "Y" ]] || die "Aborted. Re-run when ready (or SANDBOX_AUTO_APPROVE=1)."
fi

terraform apply -input=false "${PLAN_FILE}"

cat <<EOF

------------------------------------------------------------
SANDBOX IS UP
------------------------------------------------------------
Prefix:     ${NAME_PREFIX}
Account:    ${ACCOUNT_ID}
Region:     ${AWS_REGION_VALUE}
State:      local (.terraform / terraform.tfstate) — not shared
Tfvars:     .sandbox/terraform.tfvars

Quick checks:
  terraform output deployment_mode
  terraform output account_a_role_b_arn
  terraform output account_b_role_c_arn
  terraform output ci_policy_json
  terraform output sandbox_smoke_commands

Assume roleB (admin credentials):
  aws sts assume-role \\
    --role-arn "\$(terraform output -raw account_a_role_b_arn)" \\
    --role-session-name sandbox-roleb

Teardown when done:
  make sandbox-down
------------------------------------------------------------
EOF
